import { Schema } from "effect";

export const ErrorCode = {
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_EXISTS: "SESSION_EXISTS",
  DAEMON_ALREADY_RUNNING: "DAEMON_ALREADY_RUNNING",
  DAEMON_NOT_RUNNING: "DAEMON_NOT_RUNNING",
  DAEMON_SPAWN_FAILED: "DAEMON_SPAWN_FAILED",
  GIT_DIRTY: "GIT_DIRTY",
  GIT_FAILED: "GIT_FAILED",
  WORKTREE_FAILED: "WORKTREE_FAILED",
  BENCHMARK_FAILED: "BENCHMARK_FAILED",
  BENCHMARK_TIMEOUT: "BENCHMARK_TIMEOUT",
  METRIC_PARSE_FAILED: "METRIC_PARSE_FAILED",
  BENCHMARK_TAMPERED: "BENCHMARK_TAMPERED",
  AGENT_FAILED: "AGENT_FAILED",
  AGENT_TIMEOUT: "AGENT_TIMEOUT",
  BUDGET_EXHAUSTED: "BUDGET_EXHAUSTED",
  WRITE_FAILED: "WRITE_FAILED",
  READ_FAILED: "READ_FAILED",
  LOCK_FAILED: "LOCK_FAILED",
  LOCK_STALE: "LOCK_STALE",
  RECONCILIATION_FAILED: "RECONCILIATION_FAILED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export class XpError extends Schema.TaggedErrorClass<XpError>()("XpError", {
  message: Schema.String,
  code: Schema.Literals([
    ErrorCode.SESSION_NOT_FOUND,
    ErrorCode.SESSION_EXISTS,
    ErrorCode.DAEMON_ALREADY_RUNNING,
    ErrorCode.DAEMON_NOT_RUNNING,
    ErrorCode.DAEMON_SPAWN_FAILED,
    ErrorCode.GIT_DIRTY,
    ErrorCode.GIT_FAILED,
    ErrorCode.WORKTREE_FAILED,
    ErrorCode.BENCHMARK_FAILED,
    ErrorCode.BENCHMARK_TIMEOUT,
    ErrorCode.METRIC_PARSE_FAILED,
    ErrorCode.BENCHMARK_TAMPERED,
    ErrorCode.AGENT_FAILED,
    ErrorCode.AGENT_TIMEOUT,
    ErrorCode.BUDGET_EXHAUSTED,
    ErrorCode.WRITE_FAILED,
    ErrorCode.READ_FAILED,
    ErrorCode.LOCK_FAILED,
    ErrorCode.LOCK_STALE,
    ErrorCode.RECONCILIATION_FAILED,
  ]),
}) {}
